POST http://localhost:3001/api/login
Content-Type: application/json

{
 "username": "hiAlanDev", 
 "password" : "alan"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
 "username": "testCell", 
 "password" : "testCrazy"
}